max_mean_error: 0.1
max_std_dev: 1
data_topic: "mavros/imu/data"
temperature_topic: "mavros/imu/temperature_imu"
odom_topic: "robotnik_base_control/odom"
mavros_state_topic: "mavros/state"
temperature_variation_for_calibration: 2
calibration_only_under_demand: false
period_between_checkings: 60
period_of_data_gathering: 5
duration_of_calibration: 40

calibration_odom_constraint: true
calibration_by_angular_velocity_deviation: false
calibration_by_temperature: true
